### ISSUE TITLE
ReferenceError: System is not defined

### ISSUE THREAD

**Issue by ahadyekta** [isomorphic-microfrontends/navbar#19]
I tried to run root-config and navbar locally, it shows this error on terminal : 
```
@isomorphic-mf/navbar failed to render.
ReferenceError: System is not defined
```
the root-config works locally and the issue is from navbar as it doesn't work either when I override the import urls of navbar in deployed demo. 
My node version : v16.6.2

**Comment by internettrans** [comment]
Works for me, make sure to use pnpm and follow the instructions.
