### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by DanielCaris** [isomorphic-microfrontends/navbar#21]
Hi!, it is possible give support to typescript to this example?.

I get this errors when a I tried give support to typescript:

`Error: systemjs-webpack-interop: There is no such module '@isomorphic/navbar' in the SystemJS registry. Did you misspell the name of your module?`

Any ideas? 😃

**Comment by internettrans** [comment]
I don't have plans to refactor this project to typescript. The error you shared is a runtime error, not a typescript error. It indicates that your import map doesn't have `@isomorphic/navbar` in it.
